// Shared admin authorization. Existing role=admin is retained for session compatibility.
export const adminLevel=u=>u.admin_level||'root';
export const childLevels=u=>adminLevel(u)==='root'?['senior','master','player']:adminLevel(u)==='senior'?['master','player']:['player'];
const TREE=`WITH RECURSIVE team AS (SELECT id FROM users WHERE parent_id=$1 UNION ALL SELECT u.id FROM users u JOIN team t ON u.parent_id=t.id)`;
export function adminService({q,one,fail,int,reqKey,strongUser,passOk,passwordHash,move,ensureDay,settle,now,localDay}){
 const root=a=>{if(a.role!=='admin'||adminLevel(a)!=='root')fail(403,'Owner Admin သာ လုပ်ဆောင်နိုင်ပါသည်။')};
 async function visible(c,a){if(adminLevel(a)==='root')return(await q(c,"SELECT id FROM users WHERE id<>$1",[a.id])).rows.map(x=>x.id);return(await q(c,TREE+' SELECT id FROM team',[a.id])).rows.map(x=>x.id)}
 async function create(c,a,data){const level=data.level||'player';if(!childLevels(a).includes(level))fail(403,'ဤအဆင့် account ကို ဖန်တီးခွင့်မရှိပါ။');if(!strongUser(data.username)||!passOk(data.password))fail(400,'Username / Password သတ်မှတ်ချက် မမှန်ပါ။');const h=await passwordHash(data.password);let u;try{u=await one(c,'INSERT INTO users(username,password,role,admin_level,parent_id) VALUES($1,$2,$3,$4,$5) RETURNING id',[data.username.toLowerCase(),h,level==='player'?'player':'admin',level==='player'?null:level,a.id])}catch(e){if(e.code==='23505')fail(409,'Username ရှိပြီးသားပါ။');throw e}await q(c,'INSERT INTO audit(actor,action,detail) VALUES($1,$2,$3)',[a.id,'create_user',JSON.stringify({user_id:u.id,username:data.username.toLowerCase(),level,parent_id:a.id})]);return{id:u.id}}
 async function adjust(c,a,data){const {user_id,delta,note,key}=data;if(!int(user_id,1,2**31)||!int(delta,-1e9,1e9)||!delta||typeof note!=='string'||note.trim().length<5||note.length>240||!reqKey(key))fail(400,'Token အချက်အလက် မမှန်ပါ။');const u=await one(c,'SELECT * FROM users WHERE id=$1',[user_id]);if(!u||u.id===a.id||u.role==='admin'&&adminLevel(u)==='root'||adminLevel(a)!=='root'&&u.parent_id!==a.id)fail(403,'ဤ account ကို Token ပြောင်းလဲခွင့်မရှိပါ။');const ref='adjust:'+a.id+':'+key,old=await one(c,'SELECT * FROM ledger WHERE ref=$1',[ref]);if(old){if(old.user_id!==user_id||Number(old.delta)!==delta||old.note!==note)fail(409,'Request key ကို မတူသောအချက်အလက်ဖြင့် သုံးပြီးသားပါ။');return{duplicate:true}}
 // Non-owner transfers conserve the total balance; both sides commit or roll back together.
 if(adminLevel(a)!=='root')await move(c,a.id,-delta,'transfer',ref+':sender',note,a.id);
 await move(c,user_id,delta,'admin',ref,note,a.id);await q(c,'INSERT INTO audit(actor,action,detail) VALUES($1,$2,$3)',[a.id,'adjust',JSON.stringify({user_id,delta,note,mode:adminLevel(a)==='root'?'owner_adjustment':'transfer'})]);return{duplicate:false}}
 async function schedule(c,a,data){root(a);const {draw_id,result}=data;if(!int(draw_id,1,2**31))fail(400,'Draw မမှန်ပါ။');await ensureDay(c);const d=await one(c,'SELECT * FROM draws WHERE id=$1 FOR UPDATE',[draw_id]);if(!d)fail(404,'Draw မတွေ့ပါ။');if(typeof result!=='string'||!new RegExp('^[0-9]{'+d.market[0]+'}$').test(result))fail(400,'အနိုင်ရဂဏန်းအရေအတွက် မမှန်ပါ။');if(d.status==='settled'){if(d.result===result)return{duplicate:true,published:true};fail(409,'ထုတ်ပြန်ပြီးသားရလဒ်ကို ပြန်ပြင်မရပါ။')}
 const old=await one(c,'SELECT * FROM scheduled_results WHERE draw_id=$1',[draw_id]);if(old){if(old.result!==result)fail(409,'အတည်ပြုသိမ်းထားသောရလဒ်ကို ပြန်ပြင်မရပါ။');await publishDue(c);return{duplicate:true}}await q(c,'INSERT INTO scheduled_results(draw_id,result,actor,created_at) VALUES($1,$2,$3,$4)',[draw_id,result,a.id,now()]);await q(c,'INSERT INTO audit(actor,action,detail) VALUES($1,$2,$3)',[a.id,'schedule_result',JSON.stringify({draw_id,publish_at:d.cutoff})]);await publishDue(c);return{ok:true,publish_at:d.cutoff}}
 async function publishDue(c){const due=(await q(c,`SELECT r.*,d.cutoff FROM scheduled_results r JOIN draws d ON d.id=r.draw_id WHERE d.status<>'settled' AND d.cutoff<=$1 ORDER BY d.cutoff,d.id FOR UPDATE OF d`,[now()])).rows;for(const r of due){await settle(c,{id:r.actor},{draw_id:r.draw_id,result:r.result,source:'အတည်ပြုရလဒ်'});const published=new Date(Math.max(new Date(r.created_at).getTime(),new Date(r.cutoff).getTime()));await q(c,'UPDATE draws SET settled_at=$1 WHERE id=$2',[published,r.draw_id])}}
 async function state(c,a){await ensureDay(c);await publishDue(c);const ids=await visible(c,a);const users=(await q(c,'SELECT id,username,role,admin_level,parent_id,balance,active,daily_limit FROM users WHERE id=ANY($1::bigint[]) ORDER BY id',[ids])).rows.map(u=>({...u,can_adjust:adminLevel(a)==='root'||u.parent_id===a.id}));const current=await one(c,'SELECT balance FROM users WHERE id=$1',[a.id]);return{admin:a.username,level:adminLevel(a),balance:current.balance,create_levels:childLevels(a),day:localDay(),users,ledger:(await q(c,'SELECT id,delta,balance_after,kind,note,created_at FROM ledger WHERE user_id=$1 ORDER BY id DESC LIMIT 100',[a.id])).rows,draws:adminLevel(a)==='root'?(await q(c,`SELECT d.id,d.day::text,d.market,d.status,d.cutoff,r.result AS scheduled_result FROM draws d LEFT JOIN scheduled_results r ON r.draw_id=d.id WHERE d.status<>'settled' ORDER BY d.day DESC,d.id LIMIT 100`)).rows:[],audit:(await q(c,`SELECT * FROM audit WHERE $1::boolean OR (actor=ANY($2::bigint[]) AND action NOT IN ('schedule_result','settle')) ORDER BY id DESC LIMIT 200`,[adminLevel(a)==='root',[a.id,...ids]])).rows}}
 async function report(c,a,params){const ids=await visible(c,a),day=params.get('day')||localDay(),market=params.get('market')||'',number=params.get('number')||'',player=Number(params.get('player')||0),sort=params.get('sort')==='count'?'entries':'tokens',page=Number(params.get('page')||1);if(!/^\d{4}-\d{2}-\d{2}$/.test(day)||market&&!['2D','3D','4D'].includes(market)||number&&!/^[0-9]{2,4}$/.test(number)||!int(player,0,2**31)||!int(page,1,100000))fail(400,'Filter အချက်အလက် မမှန်ပါ။');if(player&&!ids.includes(player))fail(403,'ဤ Player ကို ကြည့်ခွင့်မရှိပါ။');const args=[ids,day,market,number,player];const from=`FROM bets b JOIN users u ON u.id=b.user_id JOIN draws d ON d.id=b.draw_id WHERE u.role='player' AND u.id=ANY($1::bigint[]) AND d.day=$2::date AND ($3='' OR d.market=$3) AND ($4='' OR b.number=$4) AND ($5::bigint=0 OR b.user_id=$5)`;
 const totals=await one(c,'SELECT COUNT(*)::bigint AS entries,COALESCE(SUM(b.stake),0)::bigint AS tokens '+from,args);const groups=(await q(c,`SELECT d.market,b.number,COUNT(*)::bigint AS entries,SUM(b.stake)::bigint AS tokens ${from} GROUP BY d.market,b.number ORDER BY ${sort} DESC,d.market,b.number LIMIT 100`,args)).rows;const bets=(await q(c,`SELECT b.id,u.username,d.day::text,d.market,b.number,b.stake,b.payout,b.created_at ${from} ORDER BY b.id DESC LIMIT 100 OFFSET $6`,[...args,(page-1)*100])).rows;return{day,totals,groups,bets,page,pages:Math.max(1,Math.ceil(Number(totals.entries)/100))}}
 return{create,adjust,schedule,publishDue,state,report};
}
