export function adminPage(){return String.raw`<!doctype html><html lang="my"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dubai Lottery Admin</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#091122;color:#eef3ff;font:14px/1.8 system-ui,"Noto Sans Myanmar",sans-serif}main{max-width:1080px;margin:auto;padding:22px 16px}h1{font-size:25px;margin:0}h2{font-size:18px;margin:0 0 14px}p{margin:7px 0}.card{background:#141f36;border:1px solid #2b3b55;border-radius:17px;padding:20px;margin:16px 0}input,select,button{font:inherit;border-radius:10px;padding:11px}input,select{width:100%;min-width:0;background:#0c1629;color:#fff;border:1px solid #384963;margin:5px 0 12px}label{color:#aab8d0;font-size:12px;display:block}button{border:0;background:#ffd17a;color:#271b06;font-weight:750;cursor:pointer}button:disabled{opacity:.4;cursor:default}.secondary{background:#293b55;color:#fff}.hidden{display:none!important}.grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.grid .card{margin:0}.entry{display:flex;justify-content:space-between;gap:10px;padding:12px 0;border-top:1px solid #2d3b55}.muted,small{color:#a6b4cc}.error{color:#ffb0bd}.header,.account{display:flex;align-items:center;justify-content:space-between;gap:12px}.balance{color:#ffd17a;font-size:25px;font-weight:800}.badge{display:inline-block;padding:3px 8px;background:#253650;border-radius:7px;font-size:11px;color:#ffda99}.filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.stats{display:flex;gap:18px;padding:12px;background:#0e192d;border-radius:10px;margin:12px 0}.stats b{color:#ffd17a}.table-wrap{overflow:auto;max-height:480px}table{width:100%;border-collapse:collapse;white-space:nowrap;font-size:12px}th,td{text-align:left;padding:10px 12px;border-bottom:1px solid #2b3b55}th{background:#17263e;color:#adc1df;position:sticky;top:0}.pager{display:flex;justify-content:space-between;align-items:center;margin-top:14px}.message{position:fixed;bottom:20px;left:50%;transform:translateX(-50%);padding:13px 18px;max-width:94%;border-radius:12px;border:1px solid #6981a3;background:#243853;z-index:10}.login{max-width:440px;margin:40px auto}.summary{font-size:12px;color:#b9c8df;border-left:3px solid #ffd17a;padding-left:12px}.full{width:100%}@media(max-width:700px){.grid{grid-template-columns:1fr}.filters{grid-template-columns:1fr 1fr}.card{padding:15px}h1{font-size:21px}.header{align-items:flex-start}.account{flex-wrap:wrap}}
</style></head><body><main><div class="header"><div><h1>Dubai Lottery Admin</h1><small>Accounts · Tokens · Betting reports</small></div><button id="out" class="secondary hidden">ထွက်မယ်</button></div>
<section id="login" class="card login"><h2>Admin Login</h2><form id="lf"><label for="u">Username</label><input id="u" autocomplete="username" required maxlength="32"><label for="p">Password</label><input id="p" type="password" autocomplete="current-password" required minlength="12" maxlength="128"><button class="full">ဝင်မယ်</button><p id="err" class="error" role="alert"></p></form></section>
<div id="app" class="hidden"><section class="card account"><div><b id="adminName"></b> <span id="adminLevel" class="badge"></span><p id="scope" class="muted"></p></div><div><small>သင့် Token လက်ကျန်</small><div class="balance" id="balance"></div></div></section>
<div class="grid"><section class="card"><h2>အကောင့်အသစ် ဖန်တီးမယ်</h2><form id="cf"><label for="level">အကောင့်အဆင့်</label><select id="level"></select><label for="nu">Username</label><input id="nu" required minlength="3" maxlength="32" autocomplete="off"><label for="np">Password (အနည်းဆုံး ၁၂ လုံး)</label><input id="np" type="password" required minlength="12" maxlength="128" autocomplete="new-password"><button>ဖန်တီးမယ်</button></form></section>
<section class="card"><h2>Token ဖြည့် / နုတ်</h2><p class="summary" id="transferHelp"></p><form id="af"><label for="au">လက်အောက်အကောင့်</label><select id="au" required></select><label for="delta">Token (+ ဖြည့် / − နုတ်)</label><input id="delta" type="number" step="1" required><label for="reason">စာရင်းအကြောင်းပြချက်</label><input id="reason" required minlength="5" maxlength="240"><button>အတည်ပြုမယ်</button></form></section></div>
<section id="resultPanel" class="card hidden"><h2>ရလဒ် ကြိုတင်သိမ်း / ထုတ်ပြန်မယ်</h2><p class="summary">2D ညနေ ၆ / 3D ည ၇ / 4D ည ၈ နာရီ (မြန်မာချိန်)။ ကြိုသိမ်းထားလျှင် သတ်မှတ်ချိန်မတိုင်မီ Player မမြင်ရပါ။ အတည်ပြုသိမ်းပြီး ဂဏန်းကို ပြန်ပြင်မရပါ။</p><form id="sf"><label for="draw">ပွဲစဉ်</label><select id="draw" required></select><label for="result">အနိုင်ရဂဏန်း</label><input id="result" inputmode="numeric" maxlength="4" required><p id="scheduleStatus" class="muted"></p><button id="saveResult">အတည်ပြုပြီး သိမ်းမယ်</button></form></section>
<section class="card"><h2>Player ကံစမ်းစာရင်း</h2><form id="filters"><div class="filters"><div><label for="reportDay">ရက်စွဲ</label><input id="reportDay" type="date" required></div><div><label for="reportMarket">အမျိုးအစား</label><select id="reportMarket"><option value="">အားလုံး</option><option>2D</option><option>3D</option><option>4D</option></select></div><div><label for="reportPlayer">Player</label><select id="reportPlayer"></select></div><div><label for="reportNumber">ဂဏန်း (အစသုညပါ)</label><input id="reportNumber" inputmode="numeric" maxlength="4" placeholder="ဥပမာ 07"></div><div><label for="reportSort">အများဆုံးအစဉ်</label><select id="reportSort"><option value="tokens">ထိုးထားသော Token အများဆုံး</option><option value="count">ကံစမ်းအကြိမ်ရေ အများဆုံး</option></select></div></div><button>စာရင်းကြည့်မယ်</button></form><p id="reportError" class="error"></p><div id="totals" class="stats"></div><h2>ဂဏန်းအလိုက် စုစုပေါင်း</h2><small>Filter နှင့်ကိုက်ညီသော ထိပ်ဆုံး ဂဏန်း ၁၀၀</small><div id="numbers" class="table-wrap"></div><h2 style="margin-top:24px">တစ်ဦးချင်း ကံစမ်းမှတ်တမ်း</h2><div id="bets" class="table-wrap"></div><div class="pager"><button id="prev" class="secondary">ရှေ့</button><span id="pageNo"></span><button id="next" class="secondary">နောက်</button></div></section>
<section class="card"><h2>လက်အောက်အကောင့်များ</h2><div id="users" class="table-wrap"></div></section><section class="card"><h2>သင့် Token မှတ်တမ်း</h2><div id="ledger" class="table-wrap"></div></section><section class="card"><h2>လုပ်ဆောင်မှုမှတ်တမ်း</h2><div id="audit" class="table-wrap"></div></section></div></main><div id="message" class="message hidden" role="status"></div><script>
'use strict';const $=x=>document.getElementById(x),esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>Number(n).toLocaleString('en-US'),key=()=>crypto.randomUUID().replaceAll('-',''),mm=x=>String(x).replace(/[၀-၉]/g,c=>'၀၁၂၃၄၅၆၇၈၉'.indexOf(c));
const labels={root:'Owner Admin',senior:'Senior Admin',master:'Master Admin',player:'Player'};let state=null,busy=false,pendingAdjust=null,page=1,pages=1;
function msg(t){$('message').textContent=t;$('message').classList.remove('hidden');setTimeout(()=>$('message').classList.add('hidden'),5000)}
async function api(p,d){const r=await fetch('/admin/api/'+p,{method:d?'POST':'GET',credentials:'same-origin',headers:d?{'Content-Type':'application/json','X-Lottery-Admin':'1'}:{},body:d?JSON.stringify(d):undefined});const b=await r.json();if(!r.ok){const e=new Error(b.error||'Request failed');e.status=r.status;throw e}return b}
function table(head,rows){return '<table><thead><tr>'+head.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(cell=>'<td>'+esc(cell)+'</td>').join('')+'</tr>').join('')+'</tbody></table>'+(rows.length?'':'<p class="muted">မှတ်တမ်း မရှိသေးပါ။</p>')}
function options(id,items,empty=false){const old=$(id).value;$(id).innerHTML=(empty?'<option value="">အားလုံး</option>':'')+items.map(([v,l])=>'<option value="'+esc(v)+'">'+esc(l)+'</option>').join('');if([...$(id).options].some(o=>o.value===old))$(id).value=old}
function showLogin(){state=null;$('login').classList.remove('hidden');$('app').classList.add('hidden');$('out').classList.add('hidden')}
function resultSelection(){const d=state?.draws.find(x=>String(x.id)===$('draw').value);$('result').value=d?.scheduled_result||'';$('result').disabled=!!d?.scheduled_result;$('saveResult').disabled=busy||!d||!!d.scheduled_result;$('scheduleStatus').textContent=d?.scheduled_result?'ကြိုသိမ်းထားပြီး · '+d.scheduled_result+' · သတ်မှတ်ချိန်မှ ထုတ်ပြန်မည်။':d?'ထွက်ချိန် · '+new Date(d.cutoff).toLocaleString('en-GB',{timeZone:'Asia/Yangon'}):'မထုတ်ပြန်ရသေးသောပွဲ မရှိပါ။'}
async function refresh(){try{state=await api('state');$('login').classList.add('hidden');$('app').classList.remove('hidden');$('out').classList.remove('hidden');$('adminName').textContent=state.admin;$('adminLevel').textContent=labels[state.level];$('balance').textContent=fmt(state.balance);$('scope').textContent=state.level==='root'?'အကောင့်အားလုံးကို စီမံနိုင်သည်။':'မိမိလက်အောက်အကောင့်များကိုသာ ကြည့်နိုင်သည်။';$('transferHelp').textContent=state.level==='root'?'လက်အောက် Admin / Player အကောင့်များကို Token ဖြည့် / နုတ်နိုင်သည်။':'Token ဖြည့်ပေးလျှင် သင့်လက်ကျန်မှ နုတ်မည်။ ပြန်နုတ်ယူလျှင် သင့်လက်ကျန်ထဲ ပြန်ဝင်မည်။';options('level',state.create_levels.map(l=>[l,labels[l]]));options('au',state.users.filter(u=>u.can_adjust).map(u=>[u.id,u.username+' · '+labels[u.role==='player'?'player':u.admin_level]+' · '+fmt(u.balance)]));options('reportPlayer',state.users.filter(u=>u.role==='player').map(u=>[u.id,u.username]),true);$('resultPanel').classList.toggle('hidden',state.level!=='root');options('draw',state.draws.map(d=>[d.id,d.day+' · '+d.market+(d.scheduled_result?' · သိမ်းပြီး':'')]));resultSelection();if(!$('reportDay').value)$('reportDay').value=state.day;const names=Object.fromEntries(state.users.map(u=>[u.id,u.username]));$('users').innerHTML=table(['Username','အဆင့်','ဖန်တီးသူ','Token'],state.users.map(u=>[u.username,labels[u.role==='player'?'player':u.admin_level],names[u.parent_id]||state.admin,fmt(u.balance)]));$('ledger').innerHTML=table(['အချိန်','အကြောင်းပြချက်','အဝင်/အထွက်','လက်ကျန်'],state.ledger.map(l=>[new Date(l.created_at).toLocaleString('en-GB',{timeZone:'Asia/Yangon'}),l.note,fmt(l.delta),fmt(l.balance_after)]));$('audit').innerHTML=table(['အချိန်','လုပ်ဆောင်မှု','အသေးစိတ်'],state.audit.map(a=>[new Date(a.created_at).toLocaleString('en-GB',{timeZone:'Asia/Yangon'}),a.action,JSON.stringify(a.detail)]))}catch(e){if(e.status===401)showLogin();else msg(e.message)}}
async function report(){if(!state)return;$('reportError').textContent='';try{const params=new URLSearchParams({day:$('reportDay').value,market:$('reportMarket').value,player:$('reportPlayer').value,number:mm($('reportNumber').value.trim()),sort:$('reportSort').value,page:String(page)});const r=await api('bets?'+params);pages=r.pages;$('totals').innerHTML='<span>ကံစမ်းမှု <b>'+fmt(r.totals.entries)+'</b></span><span>Token စုစုပေါင်း <b>'+fmt(r.totals.tokens)+'</b></span>';$('numbers').innerHTML=table(['အမျိုးအစား','ဂဏန်း','အကြိမ်ရေ','Token'],r.groups.map(g=>[g.market,g.number,fmt(g.entries),fmt(g.tokens)]));$('bets').innerHTML=table(['Receipt','Player','ရက်စွဲ','အမျိုးအစား','ဂဏန်း','Token','ပေါက်ကြေး'],r.bets.map(b=>[b.id,b.username,b.day,b.market,b.number,fmt(b.stake),fmt(b.payout)]));$('pageNo').textContent=page+' / '+pages;$('prev').disabled=page<=1;$('next').disabled=page>=pages}catch(e){$('reportError').textContent=e.message}}
async function mutation(button,fn){if(busy)return;busy=true;button.disabled=true;try{await fn();await refresh()}catch(e){msg(e.message)}finally{busy=false;button.disabled=false;resultSelection()}}
$('lf').onsubmit=e=>{e.preventDefault();$('err').textContent='';mutation(e.submitter,async()=>{try{await api('login',{username:$('u').value,password:$('p').value});$('p').value='';await refresh();await report()}catch(x){$('err').textContent=x.message;throw x}})};
$('out').onclick=async()=>{try{await api('logout',{})}catch{}showLogin()};$('draw').onchange=resultSelection;
$('cf').onsubmit=e=>{e.preventDefault();mutation(e.submitter,async()=>{await api('create',{username:$('nu').value,password:$('np').value,level:$('level').value});$('nu').value='';$('np').value='';msg('အကောင့်ဖန်တီးပြီးပါပြီ။')})};
$('af').oninput=()=>pendingAdjust=null;$('af').onsubmit=e=>{e.preventDefault();const payload=pendingAdjust||(pendingAdjust={user_id:Number($('au').value),delta:Number($('delta').value),note:$('reason').value,key:key()});if(!confirm(fmt(payload.delta)+' Token ပြောင်းလဲမည်။'))return;mutation(e.submitter,async()=>{try{await api('adjust',payload);pendingAdjust=null;$('delta').value='';$('reason').value='';msg('Token စာရင်းပြင်ပြီးပါပြီ။')}catch(x){if(x.status<500)pendingAdjust=null;throw x}})};
$('sf').onsubmit=e=>{e.preventDefault();const result=mm($('result').value.trim());if(!confirm('ရလဒ် '+result+' ကို အတည်ပြုသိမ်းမည်။ ပြန်ပြင်မရပါ။ ထွက်ချိန်မှ Player များမြင်ရမည်။'))return;mutation(e.submitter,async()=>{await api('settle',{draw_id:Number($('draw').value),result});msg('ရလဒ် အတည်ပြုသိမ်းပြီးပါပြီ။')})};
$('filters').onsubmit=e=>{e.preventDefault();page=1;report()};$('prev').onclick=()=>{if(page>1){page--;report()}};$('next').onclick=()=>{if(page<pages){page++;report()}};refresh().then(report);
</script></body></html>`}
